### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by RichardPickman**
1. **MFA User configured (10 points)**

image

2. **Bucket and GithubActionsRole IAM role configured (30 points)**

- Bucket 
image

- GithubActionsRole
image

3. **Github Actions workflow is created (30 points)**

image

4. **Code Organization (10 points)**

   - Code is organized

5. **Verification (10 points)**

   
image
image

6. **Additional Tasks (10 points)**

- Documentation (5 points)
- Submission (5 points)

### CODE REVIEW

**Comment by Proffesor94** [comment]
Hello, please message me in Discord (pavel.shumilin) when you finish your lab. I want to finish with the checking today, if possible.

**Comment by Proffesor94** [comment]
Should I review your lab in its current state, or you are going to fix the actions workflow?

**Comment by RichardPickman** [comment]
> Should I review your lab in its current state, or you are going to fix the actions workflow?

Hey!

Thanks for message! Yeah, I think you can evaluate my work now, cuz I am not sure I'll be able to finish on time.

**Comment by RichardPickman** [comment]
> Should I review your lab in its current state, or you are going to fix the actions workflow?

But feel free to help me, if you can, of course! For some reason my terraform role created with sts:AssumeRoleWithWebIdentity doesn't work with aws credentials and I don't know why and where to dig. Here is screenshot:

image

**Comment by Proffesor94** [comment]
> > Should I review your lab in its current state, or you are going to fix the actions workflow?
> 
> But feel free to help me, if you can, of course! For some reason my terraform role created with sts:AssumeRoleWithWebIdentity doesn't work with aws credentials and I don't know why and where to dig. Here is screenshot:
> 
> image

OIDC Provider: Ensure that the OIDC provider token.actions.githubusercontent.com is registered in AWS IAM.
https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/

**Comment by Proffesor94** [comment]
Just create OIDC Provider as in the first step of the man I  sended to you in my previous message.
image

**Comment by RichardPickman** [comment]
> Just create OIDC Provider as in the ferst step of the man I sended to you in my previous message. image

Got you, my man! I'll try to solve it tomorrow

**Comment by RichardPickman** [comment]
> Just create OIDC Provider as in the first step of the man I sended to you in my previous message. image

Doesn't work even with provider. I have one, but unfortunately...

**Comment by Proffesor94** [comment]
> > Just create OIDC Provider as in the first step of the man I sended to you in my previous message. image
> 
> Doesn't work even with provider. I have one, but unfortunately...

Have you triggered GHA after you've added provider? Please do.

**Pull request merged**
